<a href="https://colab.research.google.com/github/naveenkarthikreddy/machine-learning-and-data-science/blob/main/M_D_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY ARRAYS TAKES LESS TIME WHILE COMPARING TO NORMAL LIST

numpy takes very less space while comparing with normal list 

numpy has lots of inbuilt function than normal list

numpy allows only homogeneous type elements


Version of numpy

In [ ]:
import numpy as np

print(np.__version__)

In [ ]:
# creation of numpy arrays

import numpy as np
a=[34,35,353,356]
b=np.array(a)
c=np.array([3,34,35,35,346,34,3,43])
print(b)
print(type(b))
print(c)

[ 34  35 353 356]
<class 'numpy.ndarray'>
[  3  34  35  35 346  34   3  43]


In [ ]:
import numpy as np
a=[34, 35.33, 353, 356]
print(a)

# we can change the datatype of all the elements in the numpy array
# numpy arrays are homogeneous,we can not put the things of different 
# data types in the same numpy array
b=np.array(a,dtype=str)
c=np.array(a,dtype=int)
print(b)
print(c)

[34, 35.33, 353, 356]
['34' '35.33' '353' '356']
[ 34  35 353 356]


In [ ]:
# creation of numpy array 
a=[3]
a=np.array(a*4)
print(a)

[3 3 3 3]


np.ones()
np.zeros()
this requires 2 arguments 
1 st one is size we are required and
the second is data type that is optional


In [ ]:
a=np.ones(4)
print(a)
b=np.zeros(4,dtype=float)
c=np.zeros(7,float)
# dtype is optional

print(c)

[1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0.]


CREATION OF 2D ARRAYS
we need to pass (x,y) in the size argument of the np.zeros or np.ones

In [ ]:
b=np.zeros((4,3),int)
# (4,3) is size of the array we are wanting
# int is the data type 
# dtype is optional
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


full() needs 2 arguments 
1st one is the size and 
second is thing which we wanted to fill the array

In [ ]:
a=np.full(5,3)
print(a)
b=np.full((5,5),6,str)
print(b)

[3 3 3 3 3]
[['6' '6' '6' '6' '6']
 ['6' '6' '6' '6' '6']
 ['6' '6' '6' '6' '6']
 ['6' '6' '6' '6' '6']
 ['6' '6' '6' '6' '6']]


0D
1D
2D
3D

In [ ]:

# OD ARRAY
arr = np.array(42)

# 1D ARRAY
arr = np.array([1, 2, 3, 4, 5])

# 2D ARRAY
arr = np.array([[1, 2, 3], [4, 5, 6]])

# 3D ARRAY
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

INDEXING IN NUMPY ARRAYS

In [ ]:
a=np.array([23,3,34,3,53,3346,46,4543])
# we can get the size of the array
print(a.size)


sizeOfArray=a.size


index_sum=0
# accessing of elements through index
for i in range(sizeOfArray):
  index_sum+=a[i]
print("index_sum",index_sum)  



sum=0
# accessing of elements through in
for i in a:
  sum +=i
print("sum",sum)  


8
index_sum 8051
sum 8051


accessing the elements through indexing(negative and possitive)


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr[1,1,1])
print(arr[1,1,-1])

5
6


SLICING OF NUMPY ARRAYS


In [ ]:
a=np.array([3,3,534,35,34,345,35,343,343,3,365,64])
print(a[:a.size:2])

[  3 534  34  35 343 365]


The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.


In [ ]:
a=np.zeros(5)
b=a.view()
c=a.copy()

# if we view the array the changes done in the prev array will be reflected to the viewed array
# if we copy the array the changes done in the prev array will not be reflected to the copied array
a[2]=343

print(a)
print(b)
print(c)


[  0.   0. 343.   0.   0.]
[  0.   0. 343.   0.   0.]
[0. 0. 0. 0. 0.]


SHAPE OF THE ARRAY

SHAPE WILL RETURN THE SHAPE(SIZE OF X AND SIZE OF Y) OF THE ARRAY

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


RESHAPE()

WE CAN RESHAPE THE 1D ARRAY TO 2D ARRAY BY USING THE RESHAPE()

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=a.reshape(3,3)
print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


ITTERATING 2D ARRAYS

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for i in arr:
  for j in i:
    # we can print the each element in 2d array
    print(j)
    
for i in arr:
  # we can print the single dimension array of 2d array
  print(i)    

1
2
3
4
5
6
[1 2 3]
[4 5 6]


ARANGE()
arange(1,51,2)

first value is start and second is end

third one is jump

1st value is inclusive

2nd value is exclusive


In [2]:
import numpy as np
a=np.arange(10)
print(a)
b=np.arange(1,51,2)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


linespace(0,9)

linespace(0,9,100)

both the start and end are inclusive

first value is starting value and

second value is the ending value

third one is no of samples,but it is optional

defaultly it is set to 50 samples

to know the step of the values,find the difference between the consecutive values


In [7]:
a=np.linspace(2,9)
print(a)
# by default the values are 50


b=np.linspace(2,9,77)
print(b)
step=b[1]-b[0]
print("step",step)

[2.         2.14285714 2.28571429 2.42857143 2.57142857 2.71428571
 2.85714286 3.         3.14285714 3.28571429 3.42857143 3.57142857
 3.71428571 3.85714286 4.         4.14285714 4.28571429 4.42857143
 4.57142857 4.71428571 4.85714286 5.         5.14285714 5.28571429
 5.42857143 5.57142857 5.71428571 5.85714286 6.         6.14285714
 6.28571429 6.42857143 6.57142857 6.71428571 6.85714286 7.
 7.14285714 7.28571429 7.42857143 7.57142857 7.71428571 7.85714286
 8.         8.14285714 8.28571429 8.42857143 8.57142857 8.71428571
 8.85714286 9.        ]
[2.         2.09210526 2.18421053 2.27631579 2.36842105 2.46052632
 2.55263158 2.64473684 2.73684211 2.82894737 2.92105263 3.01315789
 3.10526316 3.19736842 3.28947368 3.38157895 3.47368421 3.56578947
 3.65789474 3.75       3.84210526 3.93421053 4.02631579 4.11842105
 4.21052632 4.30263158 4.39473684 4.48684211 4.57894737 4.67105263
 4.76315789 4.85526316 4.94736842 5.03947368 5.13157895 5.22368421
 5.31578947 5.40789474 5.5        5.59210526 5

identity(a)

we can print a identity matrix of size a 


In [8]:
a=np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


np.eye(3,5)

we can get a matrix of rectangular type but that is idenetical


In [12]:
a=np.eye(3,5,dtype=int)
print(a)

b=np.eye(4)
print(b)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


random()

this will create a array of size mentioned and values are in between the 0 and 1

In [13]:
a=np.random.rand(5)
# 
print(a)

[0.24139942 0.50115711 0.90441318 0.50292777 0.51886256]


In [15]:
# if we need the values to be in the range of o to 10 
# then mutliply the array with 10 ,so the values will 
# be in between the o and 10

b=np.random.rand(5,5)*10
print(b)

[[3.73351483 8.45017554 2.74515222 1.7283556  0.64049125]
 [6.6284979  4.34702138 6.28769053 5.2793919  0.8923457 ]
 [0.02182895 6.93522665 0.91067338 6.45731877 3.49313768]
 [5.42063093 6.38105251 0.5150541  4.52695099 8.62715   ]
 [1.76906711 9.64284674 6.06187546 1.07618598 7.39683018]]


In [19]:
c=np.random.randint(5,44)
print(c)

23


SLICING IN 2d NUMPY ARRAY


In [30]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(a)
print(a[1,3])
print(a[1:3])
print(a[3][2])
print(a[1:3,2])
print(a[2:4,1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
8
[[ 5  6  7  8]
 [ 9 10 11 12]]
15
[ 7 11]
[[10 11]
 [14 15]]


random.randint(a,b,c)

it takes 3 values

first one is start 

second is ending

last one is number of value you nee

In [37]:
a=np.random.randint(1,20,10)
print(a)
b=np.random.randint(20,30,10)
a=a+2
# we can add 2 to all the elements by using this
# we will do the same operation using the code in normal list
# a=[i+2 for i in a]
print(a)
c=a+b
print(c)
print(a/b)
print(b-a)
print(a*b)
print(b**a)

[ 1  9 15 13 15  8 12 18 11 17]
[ 3 11 17 15 17 10 14 20 13 19]
[32 40 41 37 39 31 35 47 42 48]
[0.10344828 0.37931034 0.70833333 0.68181818 0.77272727 0.47619048
 0.66666667 0.74074074 0.44827586 0.65517241]
[26 18  7  7  5 11  7  7 16 10]
[ 87 319 408 330 374 210 294 540 377 551]
[               24389    12200509765705829  3321404725185740800
  7752859499445190656  7694950768433299456       16679880978201
  3243919932521508681 -3535985420588157519 -8186115360750949427
  2582043123166336389]
139


mathematical operations

In [43]:
a=np.random.randint(10,30,20)
print(a)
print(a.sum())
print(a.min())
print(a.max())
print(a.mean())
print(a.argmin())
# index of minimum element
print(a.argmax())
# index of maximum element



[26 23 15 14 21 24 19 14 28 18 18 25 27 10 26 11 26 20 15 27]
407
10
28
20.35
13
8


In [49]:
a=np.random.randint(0,3,20)
b=np.random.randint(0,3,20)
print(a>b)
print(a<b)
print(a==b)


[False False False False  True False False False False False False False
 False False False  True  True  True  True False]
[ True False  True  True False  True  True  True  True False  True  True
  True False  True False False False False  True]
[False  True False False False False False False False  True False False
 False  True False False False False False False]


In [53]:
a=np.random.randint(0,3,20)
b=np.random.randint(0,3,20)
print(np.logical_and(a,b))
print(np.logical_or(a,b))
print(np.logical_not(a,b))

[False  True False  True False  True False False False False  True False
 False  True  True False  True False False False]
[ True  True  True  True False  True  True  True  True False  True  True
 False  True  True  True  True  True False  True]
[1 0 0 0 1 0 0 1 0 1 0 0 1 0 0 1 0 0 1 0]


# BOOLEAN INDEXING

In [55]:
a=np.random.randint(1,20,10)
print(a)
print(a>10)

[ 4 16 16  6  4  6  9  9  1 17]
[False  True  True False False False False False False  True]


print the elements of the arrays where the elements of the given array are greater than 10

In [57]:
b=np.random.randint(1,20,10)
bool_array=b>10
new_arr=b[bool_array]
print(new_arr)
new_array=b[b>10]
print(new_array)

[11 17 11 11 16]
[11 17 11 11 16]


where()
it is used to find the index of a element

In [62]:
a=np.random.randint(1,4,20)
print(a)

b=np.where(a==3)
print(b)

[3 1 2 1 2 1 2 2 2 3 2 2 3 2 3 3 3 3 1 3]
(array([ 0,  9, 12, 14, 15, 16, 17, 19]),)


In [63]:
a=np.random.randint(1,15,20)
print(a)
b=np.where(a>10)
print(b)

[ 3  1 13  6 14 11  9 11  1 12  2  2  8  9 12  5  8  4  9 11]
(array([ 2,  4,  5,  7,  9, 14, 19]),)


FOR 2D ARRAYS


In [66]:
a=np.random.randint(1,20,(5,6))
print(a)
bool_arr=a>10
print(bool_arr)
print(a[bool_arr])


[[17  5  4  3 11  3]
 [14 12  5 17  2  8]
 [ 7 14  7 18 12  1]
 [19 13  7  7  6 17]
 [18  3 15  8 12 11]]
[[ True False False False  True False]
 [ True  True False  True False False]
 [False  True False  True  True False]
 [ True  True False False False  True]
 [ True False  True False  True  True]]
[17 11 14 12 17 14 18 12 19 13 17 18 15 12 11]


change the elements to 100 if those are greater than 15

In [69]:
a=np.random.randint(1,20,(5,5))
print(a)
bool_arr=a>15
a[bool_arr]=100
print(a)


[[11 15 15  9  2]
 [13 13 12 16  7]
 [10  7 17 18 13]
 [ 6 18 14 14  9]
 [ 5  6 13 18  4]]
[[ 11  15  15   9   2]
 [ 13  13  12 100   7]
 [ 10   7 100 100  13]
 [  6 100  14  14   9]
 [  5   6  13 100   4]]


In [81]:
a=np.random.randint(1,3,(5,5))
print(a)
# changing the values in the 3rd column if there is 1 to 100
bool_arr=(a[:,2]==1)
print(bool_arr)
# print(a[:,2])
a[bool_arr,2]=100
# a[bool_arr,2] bool_arr will defines which row to select
print(a)



[[1 1 1 2 2]
 [2 2 2 1 1]
 [2 1 1 2 1]
 [1 2 2 2 2]
 [2 2 1 2 2]]
[ True False  True False  True]
[[  1   1 100   2   2]
 [  2   2   2   1   1]
 [  2   1 100   2   1]
 [  1   2   2   2   2]
 [  2   2 100   2   2]]
