<a href="https://colab.research.google.com/github/naveenkarthikreddy/machine-learning-and-data-science/blob/main/M_D_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY ARRAYS TAKES LESS TIME WHILE COMPARING TO NORMAL LIST

numpy takes very less space while comparing with normal list 

numpy has lots of inbuilt function than normal list

numpy allows only homogeneous type elements


Version of numpy

In [ ]:
import numpy as np

print(np.__version__)

In [ ]:
# creation of numpy arrays

import numpy as np
a=[34,35,353,356]
b=np.array(a)
c=np.array([3,34,35,35,346,34,3,43])
print(b)
print(type(b))
print(c)

[ 34  35 353 356]
<class 'numpy.ndarray'>
[  3  34  35  35 346  34   3  43]


In [ ]:
import numpy as np
a=[34, 35.33, 353, 356]
print(a)

# we can change the datatype of all the elements in the numpy array
# numpy arrays are homogeneous,we can not put the things of different 
# data types in the same numpy array
b=np.array(a,dtype=str)
c=np.array(a,dtype=int)
print(b)
print(c)

[34, 35.33, 353, 356]
['34' '35.33' '353' '356']
[ 34  35 353 356]


In [ ]:
# creation of numpy array 
a=[3]
a=np.array(a*4)
print(a)

[3 3 3 3]


np.ones()
np.zeros()
this requires 2 arguments 
1 st one is size we are required and
the second is data type that is optional


In [ ]:
a=np.ones(4)
print(a)
b=np.zeros(4,dtype=float)
c=np.zeros(7,float)
# dtype is optional

print(c)

[1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0.]


CREATION OF 2D ARRAYS
we need to pass (x,y) in the size argument of the np.zeros or np.ones

In [ ]:
b=np.zeros((4,3),int)
# (4,3) is size of the array we are wanting
# int is the data type 
# dtype is optional
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


full() needs 2 arguments 
1st one is the size and 
second is thing which we wanted to fill the array

In [ ]:
a=np.full(5,3)
print(a)
b=np.full((5,5),6,str)
print(b)

[3 3 3 3 3]
[['6' '6' '6' '6' '6']
 ['6' '6' '6' '6' '6']
 ['6' '6' '6' '6' '6']
 ['6' '6' '6' '6' '6']
 ['6' '6' '6' '6' '6']]


0D
1D
2D
3D

In [ ]:

# OD ARRAY
arr = np.array(42)

# 1D ARRAY
arr = np.array([1, 2, 3, 4, 5])

# 2D ARRAY
arr = np.array([[1, 2, 3], [4, 5, 6]])

# 3D ARRAY
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

INDEXING IN NUMPY ARRAYS

In [ ]:
a=np.array([23,3,34,3,53,3346,46,4543])
# we can get the size of the array
print(a.size)


sizeOfArray=a.size


index_sum=0
# accessing of elements through index
for i in range(sizeOfArray):
  index_sum+=a[i]
print("index_sum",index_sum)  



sum=0
# accessing of elements through in
for i in a:
  sum +=i
print("sum",sum)  


8
index_sum 8051
sum 8051


accessing the elements through indexing(negative and possitive)


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr[1,1,1])
print(arr[1,1,-1])

5
6


SLICING OF NUMPY ARRAYS


In [ ]:
a=np.array([3,3,534,35,34,345,35,343,343,3,365,64])
print(a[:a.size:2])

[  3 534  34  35 343 365]


The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.


In [ ]:
a=np.zeros(5)
b=a.view()
c=a.copy()

# if we view the array the changes done in the prev array will be reflected to the viewed array
# if we copy the array the changes done in the prev array will not be reflected to the copied array
a[2]=343

print(a)
print(b)
print(c)


[  0.   0. 343.   0.   0.]
[  0.   0. 343.   0.   0.]
[0. 0. 0. 0. 0.]


SHAPE OF THE ARRAY

SHAPE WILL RETURN THE SHAPE(SIZE OF X AND SIZE OF Y) OF THE ARRAY

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


RESHAPE()

WE CAN RESHAPE THE 1D ARRAY TO 2D ARRAY BY USING THE RESHAPE()

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=a.reshape(3,3)
print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


ITTERATING 2D ARRAYS

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for i in arr:
  for j in i:
    # we can print the each element in 2d array
    print(j)
    
for i in arr:
  # we can print the single dimension array of 2d array
  print(i)    

1
2
3
4
5
6
[1 2 3]
[4 5 6]
